fieldLayouts:
  31a1e163-6326-436a-9feb-53b372c086e3:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: a2129d62-1d81-4c2f-a92d-81c03ed120dc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 8823155c-e84a-4a38-af30-2cb88b705e7b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 950b3c0e-9780-4487-a881-23d96d6075d5
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: homepage
hasTitleField: false
name: Homepage
section: 735318f3-e53c-4ce1-8dad-4c7a5c7c5bee
sortOrder: 0
titleFormat: '{section.name|raw}'
