tabs:
  -
    fields:
      0cbb9736-a84b-4e83-803c-5077f56394a9:
        required: false
        sortOrder: 2
      4ca9d3b8-ff02-403a-9010-45763fcdea9f:
        required: false
        sortOrder: 3
      aef80333-1412-4130-bb84-ac3bdbbcbbe2:
        required: false
        sortOrder: 1
    name: Content
    sortOrder: 1
